%% Setting Camera test
fprintf('>To see every Camera attached use: >>imaqtool\n');
%% Setup
ListCams=webcamlist;
[index_var,~] = listdlg('PromptString','Select Camera ',...
                        'SelectionMode','single',...
                        'Name','Label Column',...
                        'ListSize',[300 200],...
                        'ListString',ListCams);
CameraName=ListCams{index_var};
Props=webcam(CameraName);

[index_res,~] = listdlg('PromptString','Select Resolution ',...
                        'SelectionMode','single',...
                        'Name','Label Column',...
                        'ListSize',[300 200],...
                        'ListString',Props.AvailableResolutions);
Props.Resolution=Props.AvailableResolutions{index_res};
% Save Configuration
writetable(table({CameraName},{Props.AvailableResolutions{index_res}},...
    'VariableNames',{'Camera' 'Resolution'}),...
    'CamSetts.csv','Delimiter',',','QuoteStrings',true)
preview(Props)
n=0;
while n<=10
    pause(1)
    n=n+1;
end

closePreview(Props)
clear('Props')

